### Register user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "123456"
}

### Login user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "123456"
}


### Get sweets without token (should fail)
# GET http://localhost:3000/api/sweets


### Get sweets with token
GET http://localhost:3000/api/sweets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGQ0MjI4Zi01NWJiLTQ0ZWItYTBiMC1iMjBiYTU4Y2IxOGUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2NDkyMTgsImV4cCI6MTc2NTY1MjgxOH0.j1VNXAht3FdhA1wXhcB3PVP7fmFEr7NBTaM5NZ68iAA
### Create sweet 
POST http://localhost:3000/api/sweets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGQ0MjI4Zi01NWJiLTQ0ZWItYTBiMC1iMjBiYTU4Y2IxOGUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2ODU4MDksImV4cCI6MTc2NTY4OTQwOX0.R1gxO3MFIjCvPhy8XEFfb3ItnElSQt-nX_kx29rEegQ
Content-Type: application/json

{
  "name": "Rasgulla",
  "category": "Bengali",
  "price": 20,
  "quantity": 10
}

### Search by category
GET http://localhost:3000/api/sweets/search?category=Bengali
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGQ0MjI4Zi01NWJiLTQ0ZWItYTBiMC1iMjBiYTU4Y2IxOGUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2NDkyMTgsImV4cCI6MTc2NTY1MjgxOH0.j1VNXAht3FdhA1wXhcB3PVP7fmFEr7NBTaM5NZ68iAA
### Search by name
GET http://localhost:3000/api/sweets/search?name=Rasgulla
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjEzOTI1Yi01YmFjLTQ4NzYtOWRjYi01Y2M4Nzg2ZmUyZDciLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU3MDA4NDYsImV4cCI6MTc2NTcwNDQ0Nn0.qNCk02zXawgG2MOyeS4tscuYFf7CYUN9T8EwTjcFG6c
### Search by price range
GET http://localhost:3000/api/sweets/search?minPrice=10&maxPrice=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGQ0MjI4Zi01NWJiLTQ0ZWItYTBiMC1iMjBiYTU4Y2IxOGUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2ODU4MDksImV4cCI6MTc2NTY4OTQwOX0.R1gxO3MFIjCvPhy8XEFfb3ItnElSQt-nX_kx29rEegQ

### Update sweet price
PUT http://localhost:3000/api/sweets/b460e09f-d794-45f7-8974-c7424063f099
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGQ0MjI4Zi01NWJiLTQ0ZWItYTBiMC1iMjBiYTU4Y2IxOGUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2ODU5ODksImV4cCI6MTc2NTY4OTU4OX0.T8VjdSVX_jQLu64-wGQuQzGt8g9OZEBnq73jgKs9f5g
Content-Type: application/json

{
  "price": 44
}


### Purchase sweet
POST http://localhost:3000/api/sweets/f79231bf-6e72-47b9-8ad8-f4b40ee5810a/purchase
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGQ0MjI4Zi01NWJiLTQ0ZWItYTBiMC1iMjBiYTU4Y2IxOGUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2ODU5ODksImV4cCI6MTc2NTY4OTU4OX0.T8VjdSVX_jQLu64-wGQuQzGt8g9OZEBnq73jgKs9f5g
Content-Type: application/json

{
  "quantity": 9
}


#--------------------------------------------------------------------------admin logins and tests
### Register admin
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "admin@sweetshop.com",
  "password": "123456"
}

### Login admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@sweetshop.com",
  "password": "123456"
}

### Restock sweet (admin only)
POST http://localhost:3000/api/sweets/12217741-ea6b-4708-986a-bfd548f40f94/restock
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjEzOTI1Yi01YmFjLTQ4NzYtOWRjYi01Y2M4Nzg2ZmUyZDciLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU3MDA4NDYsImV4cCI6MTc2NTcwNDQ0Nn0.qNCk02zXawgG2MOyeS4tscuYFf7CYUN9T8EwTjcFG6c
Content-Type: application/json

{
  "amount": 5
}

### Delete sweet (admin only)
DELETE http://localhost:3000/api/sweets/1765643339101
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGQ0MjI4Zi01NWJiLTQ0ZWItYTBiMC1iMjBiYTU4Y2IxOGUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2ODU5ODksImV4cCI6MTc2NTY4OTU4OX0.T8VjdSVX_jQLu64-wGQuQzGt8g9OZEBnq73jgKs9f5g

### protection with user tests
DELETE http://localhost:3000/api/sweets/1765643339101
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMWEwMzZiZS02MDg1LTQ1ZTUtOTQzYS00YWM5ZjJmNzkyNTYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2NTY4NjE0MSwiZXhwIjoxNzY1Njg5NzQxfQ.6-JmQAug81ZOzWMBZ1G4aRTy3cgjMyrolw2QS6Zj1ak


#--------------------------------------------------------------------------
### Health Check
GET http://localhost:3000/api/health

# ### Get sweets without token (should fail)
# GET http://localhost:3000/api/sweets



# npx prisma studio  {to open the database}





